### ISSUE TITLE
documentation how to run site

### ISSUE THREAD

**Issue by enieber** [reason-react-native/reason-react-native.github.io#15]
## The problem

This site is very good, but no has documentation on how to run this site.

## Considered solution

build documentation on how to run this site locally.

**Comment by MoOx** [comment]
Will do.

In short, clone then,

```
yarn
yarn build
yarn start
```

Then run `yarn build` for every change, there is no watcher for now.

Will make better instruction in the readme soon.

**Comment by MoOx** [comment]
That said current master branche have issues, I will fix them tonight or tomorrow so way until I close this issue :)
